#ifndef _RESOURCES_H
#define _RESOURCES_H_


#define TYPE_PLAYER 1
#define TYPE_MONSTER 1



//Characters

#define CLASS_KNIGHT 0
#define CLASS_MAGE 1
#define CLASS_ARCHER 2
#define CLASS_THIEF 3





//Packets

#define PACKET_WOODENBOX 94
#define PACKET_LEAVEPARTY 47
#define PACKET_USEITEM 33
#define PACKET_ACCEPTQUEST 51
#define PACKET_SKILLANIMATION 43
#define PACKET_USESKILL 16
#define PACKET_ANIMALUSESKILL 84



// KNIGHT SKILLS
#define SKILL_KNIGHT_LIGHTNINGSLASH 3
#define SKILL_KNIGHT_TRANSCENDENTALBLOW 5
#define SKILL_KNIGHT_SHIELDATTACK 15
#define SKILL_KNIGHT_POWERFULUPWARDSLASH 16
#define SKILL_KNIGHT_BRUTALATTACK 17
#define SKILL_KNIGHT_CALLOFDEFENSE 19
#define SKILL_KNIGHT_CALLOFRECOVERY 23
#define SKILL_KNIGHT_HALFSWING 25
#define SKILL_KNIGHT_SACRIFICE 26
#define SKILL_KNIGHT_CALLOFEVASION 27
#define SKILL_KNIGHT_PURGECONDITIONS 28
#define SKILL_KNIGHT_HEALASONE 29
#define SKILL_KNIGHT_CALLOFONTARGETPOINT 31
#define SKILL_KNIGHT_CALLOFPHYSICALATTACK 32
#define SKILL_KNIGHT_SPINSLASH 38
#define SKILL_KNIGHT_POWERFULWIDENINGWOUND 41
#define SKILL_KNIGHT_PROVOCATIONOFBLOW 42
#define SKILL_KNIGHT_SWORDDANCE 43
#define SKILL_KNIGHT_SHOUTOFDEFENSE 90
#define SKILL_KNIGHT_THEBOOMOFEARTH 91
#define SKILL_KNIGHT_SHOUTOFFIGHTINGSPIRIT 92
#define SKILL_KNIGHT_THEWAVEOFEARTH 93
// CALLS SA POJEBANE


#define SKILL_MAGE_CURE 10
#define SKILL_MAGE_CURE2 22
#define SKILL_MAGE_CURE3 35
#define SKILL_MAGE_HEAL 8
#define SKILL_MAGE_SHOCKWAVE 9
#define SKILL_MAGE_AMNESIA 61
#define SKILL_MAGE_CHAINLIGHTNING 41





#endif